### ISSUE TITLE
`VATZ` CLI command `vatz plugin start` is failing with current Example 

### ISSUE THREAD

**Issue by qkrybin** [dsrvlabs/vatz#450] opened 2023-05-25 09:45 UTC
### Checklist
- [ ] Bug from Service (Vatz)
- [x] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

### **Describe the bug**
> A clear and concise description of what the bug is.

  ```
2023-05-25T18:37:31+09:00 ERR Get > QueryRowContext.Scan Error: sql: no rows in result set module=db
Error: sql: no rows in result set
  ```
suddenly panic, when I tried to start the plugin following installation guide.
Is there any requirement that I missed? 

### **How to Reproduce**
> Steps to reproduce the behavior:

  ```
  $ ./vatz plugin start cpu_monitor
  ```

### **Expected behavior**
> A clear and concise description of what you expected to happen.

### **Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://github.com/dsrvlabs/vatz/assets/63234878/754f616c-d182-457b-8633-aaf3e5d3aa31)

**Comment by xellos00** [comment] 2023-05-25 19:03
@qkrybin 
Let's mimic this bugs with me and find out what's the cause. 
Are you available anytime between 10:00 ~ 12:00 2023-5-26 (KST)?
Please, ping me  when you check this message.

**Comment by qkrybin** [comment] 2023-05-26 00:51
```
youngbin@LT-016-youngbin vatz % make build
go build -ldflags="-X 'github.com/dsrvlabs/vatz/utils.Version=main' -X 'github.com/dsrvlabs/vatz/utils.Commit=3cf7866'" -v
youngbin@LT-016-youngbin vatz % .vatz init
zsh: command not found: .vatz
youngbin@LT-016-youngbin vatz % ./vatz init
2023-05-26T09:38:19+09:00 INF init module=main
2023-05-26T09:38:19+09:00 INF create file default.yaml module=main
2023-05-26T09:38:19+09:00 INF home path ~/.vatz module=main
2023-05-26T09:38:19+09:00 INF Load Config default.yaml module=config
2023-05-26T09:38:19+09:00 INF Plugin dir /Users/youngbin/.vatz module=main
2023-05-26T09:38:19+09:00 INF initDB /Users/youngbin/.vatz/vatz.db module=db
2023-05-26T09:38:19+09:00 INF Remove old DB file module=db
2023-05-26T09:38:19+09:00 INF Create new DB file module=db
2023-05-26T09:38:19+09:00 INF Create DB Instance module=db
youngbin@LT-016-youngbin vatz % ./vatz plugin install github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor cpu-monitor
2023-05-26T09:39:27+09:00 INF Load Config default.yaml module=config
2023-05-26T09:39:27+09:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor at /Users/youngbin/.vatz. module=plugin
2023-05-26T09:39:27+09:00 INF Installing plugin version is latest. module=plugin
2023-05-26T09:39:27+09:00 INF Create DB Instance module=db
2023-05-26T09:39:27+09:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor module=plugin
2023-05-26T09:39:32+09:00 INF AddPlugin module=db
youngbin@LT-016-youngbin vatz % ./vatz pulgin start --plugin cpu-monitor 
Error: unknown command "pulgin" for ""

Did you mean this?
        plugin

Run ' --help' for usage.
panic: unknown command "pulgin" for ""

Did you mean this?
        plugin


goroutine 1 [running]:
main.main()
        /Users/youngbin/Workspace/vatz/main.go:20 +0x44
youngbin@LT-016-youngbin vatz % ./vatz plugin start --plugin cpu-monitor
2023-05-26T09:40:35+09:00 INF Load Config default.yaml module=config
2023-05-26T09:40:35+09:00 INF Start plugin cpu-monitor  module=plugin
2023-05-26T09:40:35+09:00 INF Plugin log redirect to /Users/youngbin/.vatz/cpu-monitor.log module=plugin
2023-05-26T09:40:35+09:00 INF Create DB Instance module=db
2023-05-26T09:40:35+09:00 INF Start plugin cpu-monitor module=plugin
2023-05-26T09:40:35+09:00 INF Get cpu-monitor module=db
youngbin@LT-016-youngbin vatz % ls
LICENSE         default.yaml    manager         utils
Makefile        docs            mocks           vatz
README.md       go.mod          monitoring
cmd             go.sum          rpc
cover.out       main.go         sdk
youngbin@LT-016-youngbin vatz % lsof -i -P -n | grep LISTEN
rapportd  46700 youngbin    3u  IPv4 0x9b329dd2f08a6a1      0t0  TCP *:62498 (LISTEN)
rapportd  46700 youngbin    4u  IPv6 0x9b329dd2bf897f1      0t0  TCP *:62498 (LISTEN)
ARDAgent  46711 youngbin   10u  IPv6 0x9b329dd2bf9acf1      0t0  TCP *:3283 (LISTEN)
ControlCe 46760 youngbin   19u  IPv4 0x9b329dd2ee126a1      0t0  TCP *:7000 (LISTEN)
ControlCe 46760 youngbin   20u  IPv6 0x9b329dd2bf997f1      0t0  TCP *:7000 (LISTEN)
ControlCe 46760 youngbin   21u  IPv4 0x9b329dd2eae9c09      0t0  TCP *:5000 (LISTEN)
ControlCe 46760 youngbin   22u  IPv6 0x9b329dd2bf9a5f1      0t0  TCP *:5000 (LISTEN)
Notion    46828 youngbin   26u  IPv4 0x9b329dd2e81a6a1      0t0  TCP 127.0.0.1:53115 (LISTEN)
astxAgent 46954 youngbin    8u  IPv4 0x9b329dd2f114669      0t0  TCP *:55920 (LISTEN)
INISAFE   46961 youngbin    6u  IPv4 0x9b329dd2f137bd1      0t0  TCP 127.0.0.1:15888 (LISTEN)
veraport  46967 youngbin    3u  IPv4 0x9b329dd2edbb139      0t0  TCP 127.0.0.1:16105 (LISTEN)
INISAFECr 46973 youngbin    3u  IPv4 0x9b329dd2f111c09      0t0  TCP 127.0.0.1:4441 (LISTEN)
figma_age 46976 youngbin    3u  IPv4 0x9b329dd2eef66a1      0t0  TCP 127.0.0.1:44950 (LISTEN)
figma_age 46976 youngbin    4u  IPv4 0x9b329dd2eec26a1      0t0  TCP 127.0.0.1:44960 (LISTEN)
figma_age 46976 youngbin   11u  IPv4 0x9b329dd2ef0fbd1      0t0  TCP 127.0.0.1:18412 (LISTEN)
figma_age 46976 youngbin   39u  IPv4 0x9b329dd2ef10669      0t0  TCP 127.0.0.1:7335 (LISTEN)
CrossEXSe 46990 youngbin    5u  IPv4 0x9b329dd2f0f3139      0t0  TCP *:34581 (LISTEN)
Discord   57816 youngbin   56u  IPv4 0x9b329dd2ef58669      0t0  TCP 127.0.0.1:6463 (LISTEN)
cpu-monit 63681 youngbin    5u  IPv4 0x9b329dd2f139101      0t0  TCP 127.0.0.1:9094 (LISTEN)
youngbin@LT-016-youngbin vatz % 
```

**Comment by xellos00** [comment] 2023-05-26 00:52
> ```
> youngbin@LT-016-youngbin vatz % make build
> go build -ldflags="-X 'github.com/dsrvlabs/vatz/utils.Version=main' -X 'github.com/dsrvlabs/vatz/utils.Commit=3cf7866'" -v
> youngbin@LT-016-youngbin vatz % .vatz init
> zsh: command not found: .vatz
> youngbin@LT-016-youngbin vatz % ./vatz init
> 2023-05-26T09:38:19+09:00 INF init module=main
> 2023-05-26T09:38:19+09:00 INF create file default.yaml module=main
> 2023-05-26T09:38:19+09:00 INF home path ~/.vatz module=main
> 2023-05-26T09:38:19+09:00 INF Load Config default.yaml module=config
> 2023-05-26T09:38:19+09:00 INF Plugin dir /Users/youngbin/.vatz module=main
> 2023-05-26T09:38:19+09:00 INF initDB /Users/youngbin/.vatz/vatz.db module=db
> 2023-05-26T09:38:19+09:00 INF Remove old DB file module=db
> 2023-05-26T09:38:19+09:00 INF Create new DB file module=db
> 2023-05-26T09:38:19+09:00 INF Create DB Instance module=db
> youngbin@LT-016-youngbin vatz % ./vatz plugin install github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor cpu-monitor
> 2023-05-26T09:39:27+09:00 INF Load Config default.yaml module=config
> 2023-05-26T09:39:27+09:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor at /Users/youngbin/.vatz. module=plugin
> 2023-05-26T09:39:27+09:00 INF Installing plugin version is latest. module=plugin
> 2023-05-26T09:39:27+09:00 INF Create DB Instance module=db
> 2023-05-26T09:39:27+09:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor module=plugin
> 2023-05-26T09:39:32+09:00 INF AddPlugin module=db
> youngbin@LT-016-youngbin vatz % ./vatz pulgin start --plugin cpu-monitor 
> Error: unknown command "pulgin" for ""
> 
> Did you mean this?
>         plugin
> 
> Run ' --help' for usage.
> panic: unknown command "pulgin" for ""
> 
> Did you mean this?
>         plugin
> 
> 
> goroutine 1 [running]:
> main.main()
>         /Users/youngbin/Workspace/vatz/main.go:20 +0x44
> youngbin@LT-016-youngbin vatz % ./vatz plugin start --plugin cpu-monitor
> 2023-05-26T09:40:35+09:00 INF Load Config default.yaml module=config
> 2023-05-26T09:40:35+09:00 INF Start plugin cpu-monitor  module=plugin
> 2023-05-26T09:40:35+09:00 INF Plugin log redirect to /Users/youngbin/.vatz/cpu-monitor.log module=plugin
> 2023-05-26T09:40:35+09:00 INF Create DB Instance module=db
> 2023-05-26T09:40:35+09:00 INF Start plugin cpu-monitor module=plugin
> 2023-05-26T09:40:35+09:00 INF Get cpu-monitor module=db
> youngbin@LT-016-youngbin vatz % ls
> LICENSE         default.yaml    manager         utils
> Makefile        docs            mocks           vatz
> README.md       go.mod          monitoring
> cmd             go.sum          rpc
> cover.out       main.go         sdk
> youngbin@LT-016-youngbin vatz % lsof -i -P -n | grep LISTEN
> rapportd  46700 youngbin    3u  IPv4 0x9b329dd2f08a6a1      0t0  TCP *:62498 (LISTEN)
> rapportd  46700 youngbin    4u  IPv6 0x9b329dd2bf897f1      0t0  TCP *:62498 (LISTEN)
> ARDAgent  46711 youngbin   10u  IPv6 0x9b329dd2bf9acf1      0t0  TCP *:3283 (LISTEN)
> ControlCe 46760 youngbin   19u  IPv4 0x9b329dd2ee126a1      0t0  TCP *:7000 (LISTEN)
> ControlCe 46760 youngbin   20u  IPv6 0x9b329dd2bf997f1      0t0  TCP *:7000 (LISTEN)
> ControlCe 46760 youngbin   21u  IPv4 0x9b329dd2eae9c09      0t0  TCP *:5000 (LISTEN)
> ControlCe 46760 youngbin   22u  IPv6 0x9b329dd2bf9a5f1      0t0  TCP *:5000 (LISTEN)
> Notion    46828 youngbin   26u  IPv4 0x9b329dd2e81a6a1      0t0  TCP 127.0.0.1:53115 (LISTEN)
> astxAgent 46954 youngbin    8u  IPv4 0x9b329dd2f114669      0t0  TCP *:55920 (LISTEN)
> INISAFE   46961 youngbin    6u  IPv4 0x9b329dd2f137bd1      0t0  TCP 127.0.0.1:15888 (LISTEN)
> veraport  46967 youngbin    3u  IPv4 0x9b329dd2edbb139      0t0  TCP 127.0.0.1:16105 (LISTEN)
> INISAFECr 46973 youngbin    3u  IPv4 0x9b329dd2f111c09      0t0  TCP 127.0.0.1:4441 (LISTEN)
> figma_age 46976 youngbin    3u  IPv4 0x9b329dd2eef66a1      0t0  TCP 127.0.0.1:44950 (LISTEN)
> figma_age 46976 youngbin    4u  IPv4 0x9b329dd2eec26a1      0t0  TCP 127.0.0.1:44960 (LISTEN)
> figma_age 46976 youngbin   11u  IPv4 0x9b329dd2ef0fbd1      0t0  TCP 127.0.0.1:18412 (LISTEN)
> figma_age 46976 youngbin   39u  IPv4 0x9b329dd2ef10669      0t0  TCP 127.0.0.1:7335 (LISTEN)
> CrossEXSe 46990 youngbin    5u  IPv4 0x9b329dd2f0f3139      0t0  TCP *:34581 (LISTEN)
> Discord   57816 youngbin   56u  IPv4 0x9b329dd2ef58669      0t0  TCP 127.0.0.1:6463 (LISTEN)
> cpu-monit 63681 youngbin    5u  IPv4 0x9b329dd2f139101      0t0  TCP 127.0.0.1:9094 (LISTEN)
> youngbin@LT-016-youngbin vatz % 
> ```

I think we need to fix sample command message on the code 
plugin start must run like this way
```
./vatz plugin start --plugin cosmos-status --args "--valoperAddr=cosmosvaloper1wlagucxdxvsmvj6330864x8q3vxz4x02rmvmsu" --log ./status.log
```

**Comment by qkrybin** [comment] 2023-05-26 01:12
```
Example: "vatz plugin start pluginName",  -> Example: "vatz plugin start --plugin [pluginName] or vatz plugin start -p [pluginName] -a [arguments]"
```

**Comment by xellos00** [comment] 2023-06-16 22:27
I think this issue has been solved so I close this issue.

**Closed by xellos00** 2023-06-16 22:27 UTC
Labels: Vatz, area:plugin, type:bug
